### ISSUE TITLE
Flow error with flow-bin@0.95.1

### ISSUE THREAD

**Issue by clayne11** [fusionjs/fusion-plugin-apollo#163]
There's a Flow error with `flow-bin@0.95.1`.

### Type of issue
Flow type error

### Description

Flow error is gone.

### Current behavior

![Screen Shot 2019-03-19 at 2 47 22 PM](https://user-images.githubusercontent.com/2831444/54644163-eff50a80-4a55-11e9-947c-914be06c93f8.png)

### Expected behavior

No error

### Your environment
* fusion-plugin-apollo version:

* Node.js version (`node --version`):

* npm version (`npm --version`):

* Operating System:

**Comment by VladimirMilenko** [comment]
@KevinGrandon @ganemone 
Please, take a look at this issue. It's hanging for 21 days already.

**Comment by KevinGrandon** [comment]
Thanks for the reminder and sorry about the delay. Working on a fix for this now.
