### ISSUE TITLE
GraphQlSchemaToken is required whenever GraphQLEndpointToken is provided

### ISSUE THREAD

**Issue by dontmakemethink** [fusionjs/fusion-plugin-apollo#173]
### Type of issue
Bug

### Description
After upgrading to newest `fusion-plugin-apollo` the app throws an error regarding missing token.

### Current behavior
Throws an error about missing `GraphQlSchemaToken` while `GraphQLEndpointToken` is provided.
**Important note: I'm trying to connect to external graphql server.**

<img width="1101" alt="Screenshot 2019-04-03 at 14 54 52" src="https://user-images.githubusercontent.com/22578496/55480519-c83e9e80-5620-11e9-8bab-596d25f6de71.png">

### Expected behavior
Shouldn't throw an error :)

### Steps to reproduce
clone the repository:  [https://github.com/dontmakemethink/fusionreproduced](https://github.com/dontmakemethink/fusionreproduced)

or

1. `yarn create fusion-app my-fusion-app`
2.  follow the docs to add apollo to the project ([https://fusionjs.com/api/fusion-apollo/](https://fusionjs.com/api/fusion-apollo/))
3. use GraphQLEndpointToken

### Your environment
* fusion-plugin-apollo version:
2.0.0-3

* Node.js version (`node --version`):
v11.12.0

* npm version (`npm --version`):
6.7.0

* Operating System:
macOS Mojave 10.14.3

**Comment by maciejkorsan** [comment]
I've got the same issue

**Comment by valleywood** [comment]
Also have the same issue :(

**Comment by ganemone** [comment]
We can probably fix this by falling back to using `createRemoteExecutableSchema` if no `schema` is passed in. Feel free to submit a PR or we can fix in in the upcoming week

**Comment by szymn** [comment]
I submitted #175, which should fix this problem.
