### ISSUE TITLE
Required Token Imports don't work

### ISSUE THREAD

**Issue by chrischen** [fusionjs/fusion-plugin-apollo#187]
### Type of issue

Bug

### Description
```
import {
  ApolloRenderEnhancer,
  ApolloClientPlugin,
  ApolloClientToken,
  GraphQLEndpointToken,
} from 'fusion-plugin-apollo';
```
Imports do not work.
Same error with ApolloRenderEnhancer import.

### Current behavior

```
"export 'ApolloClientPlugin' was not found in 'fusion-plugin-apollo'
```

### Expected behavior

It should work

### Steps to reproduce
Followed instructions to register fusion-plugin-apollo on a new app created with cli.

### Your environment

* fusion-plugin-apollo version: 2.0.0-0

* Node.js version (`node --version`): 11.10.0

* npm version (`npm --version`): 6.7.0

* Operating System: MacOS 10.14.4

**Comment by KevinGrandon** [comment]
Thanks for filing an issue. I believe you will need fusion-plugin-apollo@2.0.0-8 for that token import to succeed. Please let us know if that doesn't work after upgrading and we'll take another look.

**Comment by chrischen** [comment]
I actually tried that version and got a different error (based on the install instructions). I’ll post it here when I get the chance to run it again.

**Comment by KevinGrandon** [comment]
> I actually tried that version and got a different error (based on the install instructions). I’ll post it here when I get the chance to run it again.

Gotcha, let us know what error you get with that and we'll take a look. We should be able to get it working!

**Comment by chrischen** [comment]
This is the error:
```
Error: A plugin depends on a token, but the token was not registered

Required token: FetchToken
This token is required by plugins registered with tokens: "ApolloClientToken"
```

Also the docs had an error where `GraphQLEndpointToken` was not imported in the endpoint example.

```
// @flow
import App from 'fusion-react';
import Router from 'fusion-plugin-react-router';
import Styletron from 'fusion-plugin-styletron-react';
import {RenderToken} from 'fusion-core';

import {
  ApolloRenderEnhancer,
  ApolloClientPlugin,
  ApolloClientToken,
  GraphQLEndpointToken,
} from 'fusion-plugin-apollo';

import root from './root.js';

export default () => {
  const app = new App(root);
  app.register(Styletron);
  app.register(Router);
  app.enhance(RenderToken, ApolloRenderEnhancer);
  app.register(ApolloClientToken, ApolloClientPlugin);
  app.register(GraphQLEndpointToken, 'http://website.com/graphql');
  return app;
};
```

**Comment by chrischen** [comment]
Ok I fixed it by following one of the unit tests:

```
import {FetchToken} from 'fusion-tokens';
import unfetch from 'unfetch';
...
app.register(FetchToken, unfetch);
```
